- recipe/prepare-distcheck.sh
> Make make distcheck pass

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .circleci/config.yml
- recipe/build.sh
- recipe/prepare-cppcheck.sh
- recipe/prepare-distcheck.sh
- recipe/prepare-style.sh
- recipe/prepare-valgrind.sh
- src/algebraic.cc
- src/face.cc
- src/input.cc
- src/libpolygon/face.h
- src/libpolygon/two_complex.h
- src/main.cc
- src/psimplex.cc
- src/reflect.cc
- src/sweep.cc
- src/triang.cc
- src/two_complex.cc
fixes #29. This is more of a sympton fix of course. There should be
clear ownership through smart pointers instead.
> Fix memory leak

- .circleci/config.yml
- recipe/prepare-cppcheck.sh
- recipe/prepare-distcheck.sh
- recipe/prepare-style.sh
- recipe/prepare-valgrind.sh
and generate a non-empty Linux package again.
Fixes #28.
> Build only in the build flavour

- binder/Sample.ipynb
by importing our new namespace
> Fix cling sample notebook

- .circleci/config.yml
- recipe/prepare-coverage.sh
> Run coveralls on CircleCI

- recipe/test-asv.sh
- recipe/test-build.sh
> Run ASV as part of PRs

- recipe/build-clang-format.sh
- src/libflatsurf/flatsurf/cppyy.hpp
- src/libflatsurf/flatsurf/flatsurf.hpp.in
- src/pyflatsurf/pyflatsurf/cppyy_flatsurf.py
- test/pyflatsurf/saddle_connections.py
- test/pyflatsurf/surfaces.py
and add some more complex tests
> Fix operators on vectors in Python

- src/libflatsurf/flatsurf/cppyy.hpp
- src/pyflatsurf/pyflatsurf/cppyy_flatsurf.py
- test/libflatsurf/interval_exchange_transformation.test.cc
- test/pyflatsurf/Makefile.am
- test/pyflatsurf/vector_renf_elem.py
> Fix printing of Vector<renf_elem_class>

- src/libflatsurf/vector/algorithm/base.ipp
- test/libflatsurf/vector_longlong.test.cc
> Fix printing of vectors

- src/libflatsurf/util/assert.ipp
- src/libflatsurf/util/false.ipp
- src/libflatsurf/vector/vector.cc
I think that this is the problem reported in #80.
> Fix template argument dependency for SFINAE in vector.cc

- src/libflatsurf/vector/algorithm/exact.extension.ipp
- src/libflatsurf/vector/vector.cc
- test/pyflatsurf/Makefile.am
- test/pyflatsurf/vector_gmp.py
- test/pyflatsurf/vector_mpz.py
> Add Vector<mpz_class> & Vector<mpq_class>

- src/pyflatsurf/pyflatsurf/sageflatsurf_pyflatsurf.py
- test/pyflatsurf/Makefile.am
- test/pyflatsurf/doc.py
Interface with https://github.com/videlec/sage-flatsurf
> sage-flatsurf interface

- pyflatsurf/src/pyflatsurf/cppyy_flatsurf.py
- pyflatsurf/test/vector_gmp.py
> Fix scalar multiplications from Python

- libflatsurf/flatsurf/flat_triangulation_combinatorial.hpp
- libflatsurf/src/flat_triangulation_combinatorial.cc
> Add FlatTriangulationCombinatorial::faces()

- libflatsurf/flatsurf/flat_triangulation_combinatorial.hpp
- libflatsurf/flatsurf/permutation.hpp
- libflatsurf/flatsurf/vertex.hpp
- libflatsurf/src/flat_triangulation.cc
- libflatsurf/src/flat_triangulation_combinatorial.cc
- libflatsurf/src/permutation.cc
- libflatsurf/src/saddle_connections.cc
- libflatsurf/test/flat_triangulation_combinatorial.test.cc
- libflatsurf/test/permutation.test.cc
> Return outgoing half edges in order

- libflatsurf/flatsurf/cppyy.hpp
- libflatsurf/flatsurf/edge_map.hpp
- libflatsurf/flatsurf/flat_triangulation.hpp
- libflatsurf/flatsurf/half_edge_map.hpp
- libflatsurf/src/flat_triangulation.cc
- libflatsurf/test/flat_triangulation.test.cc
- pyflatsurf/src/pyflatsurf/cppyy_flatsurf.py
- pyflatsurf/test/Makefile.am
- pyflatsurf/test/flat_triangulation.py
> Implementation FlatTriangulation::operator+(vectors)

- pyflatsurf/src/pyflatsurf/vector.py
and make flatsurf vector integration more robust
> implement decomposition of vectors into algebraic parts

- pyflatsurf/test/saddle_connections.py
iterating connections is reasonably fast now
fixes #64
> Test exact-real hexagon

- libflatsurf/flatsurf/flow_component.hpp
- libflatsurf/src/flow_component.cc
- libflatsurf/src/flow_connection.cc
- libflatsurf/src/impl/flow_connection.impl.hpp
- libflatsurf/src/lengths.cc
- news/triang-speed.rst
this speeds up FlowConnection::triangulation() substantially.
Also fix some minor typos.
> Speed up FlowConnection methods

- libflatsurf/benchmark/saddle_connections.benchmark.cc
currently, it takes a while to get the initial connections out of
SaddleConnectionsByLength. We should optimize this.
Also, we take out some benchmarks that are annoyingly slow in CI.
> Benchmark SaddleConnectionsByLength

- libflatsurf/src/Makefile.am
- libflatsurf/src/assert_connection.cc
- libflatsurf/src/flat_triangulation_collapsed.cc
- libflatsurf/src/impl/assert_connection.hpp
- libflatsurf/src/lengths.cc
- libflatsurf/src/util/assert.ipp
- news/amortized.rst
> Speed up amortized assertions

- libflatsurf/src/lengths.cc
only a very minor change that uses the same pattern when locking the
weak pointer of the state so it is obvious that nothing can go wrong
with lifetimes here.
> simplify locking code in lengths

- libflatsurf/benchmark/Makefile.am
- libflatsurf/configure.ac
- libflatsurf/environment.yml
- libflatsurf/recipe/meta.yaml
- libflatsurf/test/Makefile.am
- pyflatsurf/environment.yml
since we actually #include both by now.
> require flint and GMP

- doc/news/inf-slopes.rst
- libflatsurf/flatsurf/detail/vector_exact.hpp
- libflatsurf/src/vector.cc
- libflatsurf/test/vector.test.cc
- pyflatsurf/src/pyflatsurf/vector.py
- pyflatsurf/test/saddle_connections.py
> Identify infinite slopes in CompareSlope

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
- asv.conf.json
- doc/news/shift-connections.rst
- libflatsurf/environment.yml
- libflatsurf/flatsurf/saddle_connection.hpp
- libflatsurf/recipe/meta.yaml
- libflatsurf/src/shift_deformation_relation.cc
- libflatsurf/test/deformation.test.cc
- libflatsurf/test/flat_triangulation.test.cc
- pyflatsurf/environment.yml
- pyflatsurf/recipe/meta.yaml
- pyflatsurf/src/pyflatsurf/vector.py
- pyflatsurf/test/Makefile.am
- pyflatsurf/test/disable-pytest/pytest.py
- pyflatsurf/test/sage-doctest.sh.in
when the underlying deformation comes from a shift.
fixes #282
> implement Deformation::operator()(const SaddleConnection&)

- doc/news/osx-size-t.rst
- libflatsurf/flatsurf/flow_component.hpp
- libflatsurf/flatsurf/tracked.hpp
- libflatsurf/src/contour_decomposition.cc
- libflatsurf/src/flow_component.cc
- libflatsurf/src/flow_connection.cc
- libflatsurf/src/flow_triangulation.cc
- libflatsurf/src/impl/contour_component_state.hpp
- libflatsurf/src/impl/flow_decomposition_state.hpp
- libflatsurf/src/impl/interval_exchange_transformation.impl.hpp
- libflatsurf/src/impl/lengths.hpp
- libflatsurf/src/impl/saddle_connections_iterator.impl.hpp
- libflatsurf/src/impl/vertical.impl.hpp
- libflatsurf/src/lengths.cc
- libflatsurf/src/permutation.cc
- libflatsurf/src/saddle_connections_iterator.cc
- libflatsurf/src/util/hash.ipp
- libflatsurf/src/vector.cc
- libflatsurf/test/flat_triangulation.test.cc
- libflatsurf/test/path.test.cc
where size_t is not uint64_t but unsigned long
> fix compilation on macOS

- doc/news/eliminate-thurston-veech.rst
- libflatsurf/src/generic_retriangulation_deformation_relation.cc
- libflatsurf/src/impl/generic_retriangulation_deformation_relation.hpp
- libflatsurf/test/generators/surface_generator.hpp
- libflatsurf/test/surfaces.hpp
> Fix eliminating marked points in Thurston-Veech surfaces

- doc/news/flow-decomposition-vector.rst
- libflatsurf/flatsurf/flow_decomposition.hpp
- libflatsurf/src/flow_component.cc
- libflatsurf/src/flow_decomposition.cc
- pyflatsurf/test/flow_decomposition.py
> Implement missing FlowDecomposition::vertical()

- .github/workflows/benchmark.yml
- .github/workflows/conda.yml
- .github/workflows/coverage.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- asv.conf.json
- doc/news/macos.rst
- libflatsurf/environment.yml
- libflatsurf/src/contour_decomposition_state.cc
- pyflatsurf/environment.yml
- pyflatsurf/src/pyflatsurf/__init__.py
- pyflatsurf/src/pyflatsurf/vector.py
- pyflatsurf/test/Makefile.am
- pyflatsurf/test/bin/python.in
- pyflatsurf/test/bound.py
- pyflatsurf/test/deformation.py
- pyflatsurf/test/equivalence_class.py
- pyflatsurf/test/flat_triangulation.py
- pyflatsurf/test/flat_triangulation_combinatorial.py
- pyflatsurf/test/flow_decomposition.py
- pyflatsurf/test/half_edge.py
- pyflatsurf/test/point.py
- pyflatsurf/test/python-doctest.sh.in
- pyflatsurf/test/saddle_connections.py
- pyflatsurf/test/sage-doctest.sh.in
- pyflatsurf/test/test-env.sh.in
- pyflatsurf/test/vector_gmp.py
- pyflatsurf/test/vector_renf_elem.py
- pyflatsurf/test/vertex.py
> Run tests on macOS in CI
